# Generated by Django 3.2.9 on 2021-12-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrmodel',
            name='desc',
            field=models.TextField(blank=True, max_length=50000),
        ),
    ]
